# Generated by Django 4.0.4 on 2022-06-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Equipamento')),
                ('ipv4_or_ipv6', models.GenericIPAddressField(unique=True, verbose_name='IPv4 / IPv6')),
                ('type', models.CharField(blank=True, choices=[('Notebook', 'Notebook'), ('Computador', 'Computador'), ('Impressora', 'Impressora'), ('Roteador', 'Roteador'), ('Outros', 'Outros')], max_length=10, null=True, verbose_name='Tipo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rede.department', verbose_name='Setor')),
            ],
            options={
                'ordering': ['-ipv4_or_ipv6'],
            },
        ),
    ]
