# Generated by Django 4.0.4 on 2022-05-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('ipv4_or_ipv6', models.GenericIPAddressField(unique=True)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.equipments')),
            ],
        ),
    ]
