# Generated by Django 4.0.4 on 2022-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networks',
            options={'ordering': ['ipv4_or_ipv6']},
        ),
        migrations.AlterField(
            model_name='networks',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipamento'),
        ),
    ]
