# Generated by Django 4.0.4 on 2022-06-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0002_alter_networks_options_alter_networks_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='networks',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
