# Generated by Django 4.0.4 on 2022-06-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_networks_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networks',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='networks',
            order_with_respect_to='department',
        ),
    ]
