# Generated by Django 4.0.4 on 2022-06-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0004_alter_networks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networks',
            options={'ordering': ['department']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='networks',
            order_with_respect_to=None,
        ),
    ]
