# Generated by Django 4.0.4 on 2022-06-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0005_alter_networks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networks',
            options={'ordering': ['department', 'equipment']},
        ),
    ]
