# Generated by Django 4.0.4 on 2022-05-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('type', models.CharField(choices=[('Notebook', 'Notebook'), ('Computador', 'Computador'), ('Impressora', 'Impressora'), ('Roteador', 'Roteador'), ('Outros', 'Outros')], max_length=10, verbose_name='Tipo')),
                ('status', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
        ),
    ]
